import { db } from "../server/db";
import { counties } from "../shared/schema";

// All 67 Florida counties with their building permit requirements
const floridaCounties = [
  {
    id: "alachua",
    name: "Alachua County",
    slug: "alachua",
    websiteUrl: "https://www.alachuacounty.us/Depts/epd/Pages/epd.aspx",
    permitPhone: "(352) 374-5249",
    permitEmail: "permits@alachuacounty.us",
    description: "Alachua County Building Department handles all construction permits including residential, commercial, and industrial projects.",
  },
  {
    id: "baker",
    name: "Baker County",
    slug: "baker",
    websiteUrl: "https://www.bakercountyfl.org/departments/building_department.php",
    permitPhone: "(904) 259-5714",
    permitEmail: "building@bakercountyfl.org",
    description: "Baker County Building Department oversees building permits and inspections for all construction activities.",
  },
  {
    id: "bay",
    name: "Bay County",
    slug: "bay",
    websiteUrl: "https://www.baycountyfl.gov/179/Building-Services",
    permitPhone: "(850) 248-8250",
    permitEmail: "building@baycountyfl.gov",
    description: "Bay County Building Services Department manages construction permits and code enforcement.",
  },
  {
    id: "bradford",
    name: "Bradford County",
    slug: "bradford",
    websiteUrl: "https://www.bradfordcountyfl.gov/departments/building_department",
    permitPhone: "(904) 966-6327",
    permitEmail: "building@bradfordcountyfl.gov",
    description: "Bradford County Building Department provides permit services for residential and commercial construction.",
  },
  {
    id: "brevard",
    name: "Brevard County",
    slug: "brevard",
    websiteUrl: "https://www.brevardcounty.gov/NaturalResources/EnvironmentallyEndangeredLands/Home",
    permitPhone: "(321) 633-2069",
    permitEmail: "permits@brevardcounty.gov",
    description: "Brevard County manages building permits for the Space Coast region including special coastal requirements.",
  },
  {
    id: "broward",
    name: "Broward County",
    slug: "broward",
    websiteUrl: "https://www.broward.org/PlanningAndDevelopment/Pages/default.aspx",
    permitPhone: "(954) 765-4500",
    permitEmail: "permits@broward.org",
    description: "Broward County Planning and Development oversees one of Florida's largest building permit programs.",
  },
  {
    id: "calhoun",
    name: "Calhoun County",
    slug: "calhoun",
    websiteUrl: "https://www.calhounclerk.com/building-department",
    permitPhone: "(850) 674-4545",
    permitEmail: "building@calhounclerk.com",
    description: "Calhoun County Building Department handles building permits and inspections for rural development.",
  },
  {
    id: "charlotte",
    name: "Charlotte County",
    slug: "charlotte",
    websiteUrl: "https://www.charlottecountyfl.gov/services/building/Pages/default.aspx",
    permitPhone: "(941) 743-1201",
    permitEmail: "building@charlottecountyfl.gov",
    description: "Charlotte County Building Department serves the southwestern Florida region with comprehensive permit services.",
  },
  {
    id: "citrus",
    name: "Citrus County",
    slug: "citrus",
    websiteUrl: "https://www.citrusbocc.com/departments/building_department",
    permitPhone: "(352) 527-5211",
    permitEmail: "building@citrusbocc.com",
    description: "Citrus County Building Department manages construction permits for the Nature Coast area.",
  },
  {
    id: "clay",
    name: "Clay County",
    slug: "clay",
    websiteUrl: "https://www.claycountygov.com/departments/building",
    permitPhone: "(904) 529-8200",
    permitEmail: "building@claycountygov.com",
    description: "Clay County Building Department provides permit services for the Jacksonville metropolitan area.",
  },
  {
    id: "collier",
    name: "Collier County",
    slug: "collier",
    websiteUrl: "https://www.colliercountyfl.gov/your-government/divisions-a-e/community-and-human-services/building-review-and-permitting",
    permitPhone: "(239) 252-2400",
    permitEmail: "building@colliercountyfl.gov",
    description: "Collier County Building Review and Permitting serves the Naples area with specialized coastal construction requirements.",
  },
  {
    id: "columbia",
    name: "Columbia County",
    slug: "columbia",
    websiteUrl: "https://www.columbiacountyfla.com/departments/building_department",
    permitPhone: "(386) 758-1005",
    permitEmail: "building@columbiacountyfla.com",
    description: "Columbia County Building Department handles permits for residential and commercial development in North Florida.",
  },
  {
    id: "miami-dade",
    name: "Miami-Dade County",
    slug: "miami-dade",
    websiteUrl: "https://www.miamidade.gov/permits/home.asp",
    permitPhone: "(786) 315-2500",
    permitEmail: "permits@miamidade.gov",
    description: "Miami-Dade County operates one of the nation's largest building permit programs with specialized hurricane and coastal requirements.",
  },
  {
    id: "desoto",
    name: "DeSoto County",
    slug: "desoto",
    websiteUrl: "https://www.desotobocc.com/departments/building_department",
    permitPhone: "(863) 993-4876",
    permitEmail: "building@desotobocc.com",
    description: "DeSoto County Building Department serves the agricultural heartland of Florida with rural and agricultural building permits.",
  },
  {
    id: "dixie",
    name: "Dixie County",
    slug: "dixie",
    websiteUrl: "https://www.dixiecounty.org/building-department",
    permitPhone: "(352) 498-1200",
    permitEmail: "building@dixiecounty.org",
    description: "Dixie County Building Department manages permits for the Big Bend region of Florida.",
  },
  {
    id: "duval",
    name: "Duval County",
    slug: "duval",
    websiteUrl: "https://www.coj.net/departments/planning-and-development/building-inspection",
    permitPhone: "(904) 255-7900",
    permitEmail: "permits@coj.net",
    description: "Duval County (Jacksonville) Building Inspection Division handles permits for Florida's largest city by area.",
  },
  {
    id: "escambia",
    name: "Escambia County",
    slug: "escambia",
    websiteUrl: "https://myescambia.com/our-services/building-services",
    permitPhone: "(850) 595-4600",
    permitEmail: "building@myescambia.com",
    description: "Escambia County Building Services manages permits for the Pensacola area with Gulf Coast construction requirements.",
  },
  {
    id: "flagler",
    name: "Flagler County",
    slug: "flagler",
    websiteUrl: "https://www.flaglercounty.gov/departments/building_department",
    permitPhone: "(386) 313-4020",
    permitEmail: "building@flaglercounty.gov",
    description: "Flagler County Building Department serves the Historic Coast with specialized historic preservation requirements.",
  },
  {
    id: "franklin",
    name: "Franklin County",
    slug: "franklin",
    websiteUrl: "https://www.franklincountyflorida.com/building-department",
    permitPhone: "(850) 653-9783",
    permitEmail: "building@franklincountyflorida.com",
    description: "Franklin County Building Department manages coastal construction permits in the Forgotten Coast region.",
  },
  {
    id: "gadsden",
    name: "Gadsden County",
    slug: "gadsden",
    websiteUrl: "https://www.gadsdencountyfl.gov/departments/building_department",
    permitPhone: "(850) 875-8665",
    permitEmail: "building@gadsdencountyfl.gov",
    description: "Gadsden County Building Department serves the Quincy area with agricultural and residential permit services.",
  },
  {
    id: "gilchrist",
    name: "Gilchrist County",
    slug: "gilchrist",
    websiteUrl: "https://gilchristcounty.org/departments/building-department",
    permitPhone: "(352) 463-3170",
    permitEmail: "building@gilchristcounty.org",
    description: "Gilchrist County Building Department handles permits for rural North Central Florida development.",
  },
  {
    id: "glades",
    name: "Glades County",
    slug: "glades",
    websiteUrl: "https://www.gladescounty.org/building-department",
    permitPhone: "(863) 946-6020",
    permitEmail: "building@gladescounty.org",
    description: "Glades County Building Department manages permits for the rural Lake Okeechobee region.",
  },
  {
    id: "gulf",
    name: "Gulf County",
    slug: "gulf",
    websiteUrl: "https://www.gulfcounty-fl.gov/departments/building_department",
    permitPhone: "(850) 229-6113",
    permitEmail: "building@gulfcounty-fl.gov",
    description: "Gulf County Building Department serves the Forgotten Coast with specialized coastal construction requirements.",
  },
  {
    id: "hamilton",
    name: "Hamilton County",
    slug: "hamilton",
    websiteUrl: "https://www.hamiltoncountyfl.com/building-department",
    permitPhone: "(386) 792-1288",
    permitEmail: "building@hamiltoncountyfl.com",
    description: "Hamilton County Building Department provides permit services for the Suwannee River region.",
  },
  {
    id: "hardee",
    name: "Hardee County",
    slug: "hardee",
    websiteUrl: "https://www.hardeecounty.net/departments/building_department",
    permitPhone: "(863) 773-2161",
    permitEmail: "building@hardeecounty.net",
    description: "Hardee County Building Department serves the agricultural heartland with rural development permits.",
  },
  {
    id: "hendry",
    name: "Hendry County",
    slug: "hendry",
    websiteUrl: "https://www.hendryfla.net/departments/building_department",
    permitPhone: "(863) 675-5240",
    permitEmail: "building@hendryfla.net",
    description: "Hendry County Building Department manages permits for agricultural and rural residential development.",
  },
  {
    id: "hernando",
    name: "Hernando County",
    slug: "hernando",
    websiteUrl: "https://www.hernandocounty.us/departments/building-department",
    permitPhone: "(352) 754-4062",
    permitEmail: "building@hernandocounty.us",
    description: "Hernando County Building Department serves the Nature Coast with comprehensive construction permit services.",
  },
  {
    id: "highlands",
    name: "Highlands County",
    slug: "highlands",
    websiteUrl: "https://www.hcbcc.org/departments/building_department",
    permitPhone: "(863) 402-6730",
    permitEmail: "building@hcbcc.org",
    description: "Highlands County Building Department manages permits for the Heartland region including lake communities.",
  },
  {
    id: "hillsborough",
    name: "Hillsborough County",
    slug: "hillsborough",
    websiteUrl: "https://www.hillsboroughcounty.org/en/residents/property-owners-and-renters/building-and-development",
    permitPhone: "(813) 272-5900",
    permitEmail: "building@hillsboroughcounty.org",
    description: "Hillsborough County Building and Development Services manages permits for the Tampa Bay metropolitan area.",
  },
  {
    id: "holmes",
    name: "Holmes County",
    slug: "holmes",
    websiteUrl: "https://www.holmescountyfl.org/building-department",
    permitPhone: "(850) 547-1119",
    permitEmail: "building@holmescountyfl.org",
    description: "Holmes County Building Department serves the rural Panhandle region with agricultural and residential permits.",
  },
  {
    id: "indian-river",
    name: "Indian River County",
    slug: "indian-river",
    websiteUrl: "https://www.ircgov.com/departments/community-development/building-department",
    permitPhone: "(772) 226-1223",
    permitEmail: "building@ircgov.com",
    description: "Indian River County Building Department serves the Treasure Coast with specialized coastal construction requirements.",
  },
  {
    id: "jackson",
    name: "Jackson County",
    slug: "jackson",
    websiteUrl: "https://www.jacksoncountyfl.gov/departments/building_department",
    permitPhone: "(850) 482-9633",
    permitEmail: "building@jacksoncountyfl.gov",
    description: "Jackson County Building Department manages permits for the rural Panhandle region.",
  },
  {
    id: "jefferson",
    name: "Jefferson County",
    slug: "jefferson",
    websiteUrl: "https://www.jeffersoncountyfl.gov/departments/building_department",
    permitPhone: "(850) 342-0223",
    permitEmail: "building@jeffersoncountyfl.gov",
    description: "Jefferson County Building Department serves the historic Monticello area with preservation-focused permits.",
  },
  {
    id: "lafayette",
    name: "Lafayette County",
    slug: "lafayette",
    websiteUrl: "https://www.lafayettecountyfl.net/building-department",
    permitPhone: "(386) 294-1980",
    permitEmail: "building@lafayettecountyfl.net",
    description: "Lafayette County Building Department handles permits for the rural Suwannee River region.",
  },
  {
    id: "lake",
    name: "Lake County",
    slug: "lake",
    websiteUrl: "https://www.lakecountyfl.gov/departments/community_services/building/",
    permitPhone: "(352) 253-4900",
    permitEmail: "building@lakecountyfl.gov",
    description: "Lake County Building Division serves Central Florida with comprehensive residential and commercial permit services.",
  },
  {
    id: "lee",
    name: "Lee County",
    slug: "lee",
    websiteUrl: "https://www.leegov.com/dcd/building",
    permitPhone: "(239) 533-8895",
    permitEmail: "building@leegov.com",
    description: "Lee County Building Department serves Southwest Florida including Fort Myers with coastal construction requirements.",
  },
  {
    id: "leon",
    name: "Leon County",
    slug: "leon",
    websiteUrl: "https://www.leoncountyfl.gov/departments/development_support_environmental_management",
    permitPhone: "(850) 606-1300",
    permitEmail: "building@leoncountyfl.gov",
    description: "Leon County Development Support and Environmental Management serves the Tallahassee area.",
  },
  {
    id: "levy",
    name: "Levy County",
    slug: "levy",
    websiteUrl: "https://www.levycounty.org/departments/building_department",
    permitPhone: "(352) 486-5213",
    permitEmail: "building@levycounty.org",
    description: "Levy County Building Department serves the Nature Coast with rural and coastal development permits.",
  },
  {
    id: "liberty",
    name: "Liberty County",
    slug: "liberty",
    websiteUrl: "https://www.libertycountyfl.gov/building-department",
    permitPhone: "(850) 643-5404",
    permitEmail: "building@libertycountyfl.gov",
    description: "Liberty County Building Department manages permits for the rural Apalachicola River region.",
  },
  {
    id: "madison",
    name: "Madison County",
    slug: "madison",
    websiteUrl: "https://www.madisoncountyfl.gov/departments/building_department",
    permitPhone: "(850) 973-3176",
    permitEmail: "building@madisoncountyfl.gov",
    description: "Madison County Building Department serves North Florida with agricultural and residential permit services.",
  },
  {
    id: "manatee",
    name: "Manatee County",
    slug: "manatee",
    websiteUrl: "https://www.mymanatee.org/departments/development_services/building_safety",
    permitPhone: "(941) 748-4501",
    permitEmail: "building@mymanatee.org",
    description: "Manatee County Building Safety serves the greater Bradenton area with comprehensive construction permit services.",
  },
  {
    id: "marion",
    name: "Marion County",
    slug: "marion",
    websiteUrl: "https://www.marioncountyfl.org/departments/building_department",
    permitPhone: "(352) 438-2842",
    permitEmail: "building@marioncountyfl.org",
    description: "Marion County Building Department serves the Ocala area with equestrian and agricultural development permits.",
  },
  {
    id: "martin",
    name: "Martin County",
    slug: "martin",
    websiteUrl: "https://www.martin.fl.us/building-department",
    permitPhone: "(772) 288-5732",
    permitEmail: "building@martin.fl.us",
    description: "Martin County Building Department serves the Treasure Coast with specialized environmental and coastal requirements.",
  },
  {
    id: "monroe",
    name: "Monroe County",
    slug: "monroe",
    websiteUrl: "https://www.monroecounty-fl.gov/departments/building_department",
    permitPhone: "(305) 289-2501",
    permitEmail: "building@monroecounty-fl.gov",
    description: "Monroe County Building Department serves the Florida Keys with unique tropical and hurricane-resistant construction requirements.",
  },
  {
    id: "nassau",
    name: "Nassau County",
    slug: "nassau",
    websiteUrl: "https://www.nassaucountyfl.com/departments/building_department",
    permitPhone: "(904) 530-6300",
    permitEmail: "building@nassaucountyfl.com",
    description: "Nassau County Building Department serves the northeastern coast including Fernandina Beach with historic preservation requirements.",
  },
  {
    id: "okaloosa",
    name: "Okaloosa County",
    slug: "okaloosa",
    websiteUrl: "https://www.okaloosa.gov/departments/building_safety",
    permitPhone: "(850) 651-7260",
    permitEmail: "building@okaloosa.gov",
    description: "Okaloosa County Building Safety serves the Emerald Coast with specialized Gulf Coast construction requirements.",
  },
  {
    id: "okeechobee",
    name: "Okeechobee County",
    slug: "okeechobee",
    websiteUrl: "https://www.co.okeechobee.fl.us/departments/building_department",
    permitPhone: "(863) 763-6441",
    permitEmail: "building@co.okeechobee.fl.us",
    description: "Okeechobee County Building Department manages permits for the Lake Okeechobee region with agricultural focus.",
  },
  {
    id: "orange",
    name: "Orange County",
    slug: "orange",
    websiteUrl: "https://www.orangecountyfl.net/CulturalandParks/PermitsLicensing.aspx",
    permitPhone: "(407) 836-8550",
    permitEmail: "permits@orangecountyfl.net",
    description: "Orange County Permitting and Licensing serves the Orlando metropolitan area with high-volume construction permits.",
  },
  {
    id: "osceola",
    name: "Osceola County",
    slug: "osceola",
    websiteUrl: "https://www.osceola.org/agencies-departments/community-development/building-department/",
    permitPhone: "(407) 742-0600",
    permitEmail: "building@osceola.org",
    description: "Osceola County Building Department serves the Kissimmee area with tourism and residential development permits.",
  },
  {
    id: "palm-beach",
    name: "Palm Beach County",
    slug: "palm-beach",
    websiteUrl: "https://discover.pbcgov.org/pzb/planning/Pages/default.aspx",
    permitPhone: "(561) 233-5000",
    permitEmail: "permits@pbcgov.org",
    description: "Palm Beach County Planning, Zoning and Building serves one of Florida's largest counties with diverse construction requirements.",
  },
  {
    id: "pasco",
    name: "Pasco County",
    slug: "pasco",
    websiteUrl: "https://www.pascocountyfl.net/397/Land-Development",
    permitPhone: "(727) 847-2411",
    permitEmail: "building@pascocountyfl.net",
    description: "Pasco County Land Development manages permits for the rapidly growing Tampa Bay region.",
  },
  {
    id: "pinellas",
    name: "Pinellas County",
    slug: "pinellas",
    websiteUrl: "https://pinellas.gov/development/",
    permitPhone: "(727) 464-3888",
    permitEmail: "development@pinellas.gov",
    description: "Pinellas County Development Review Services serves the St. Petersburg-Clearwater area with dense urban development permits.",
  },
  {
    id: "polk",
    name: "Polk County",
    slug: "polk",
    websiteUrl: "https://www.polk-county.net/departments/community-development",
    permitPhone: "(863) 534-6200",
    permitEmail: "building@polk-county.net",
    description: "Polk County Community Development serves Central Florida with agricultural, residential, and commercial permits.",
  },
  {
    id: "putnam",
    name: "Putnam County",
    slug: "putnam",
    websiteUrl: "https://www.putnam-fl.com/departments/building_department",
    permitPhone: "(386) 329-0361",
    permitEmail: "building@putnam-fl.com",
    description: "Putnam County Building Department serves the St. Johns River region with rural and riverfront development permits.",
  },
  {
    id: "st-johns",
    name: "St. Johns County",
    slug: "st-johns",
    websiteUrl: "https://www.sjcfl.us/departments/building-services/",
    permitPhone: "(904) 209-2580",
    permitEmail: "building@sjcfl.us",
    description: "St. Johns County Building Services serves the Historic Coast with specialized historic preservation and coastal requirements.",
  },
  {
    id: "st-lucie",
    name: "St. Lucie County",
    slug: "st-lucie",
    websiteUrl: "https://www.stlucieco.gov/departments-services/a-z/building-department",
    permitPhone: "(772) 462-1650",
    permitEmail: "building@stlucieco.gov",
    description: "St. Lucie County Building Department serves the Treasure Coast with coastal and agricultural development permits.",
  },
  {
    id: "santa-rosa",
    name: "Santa Rosa County",
    slug: "santa-rosa",
    websiteUrl: "https://www.santarosa.fl.gov/departments/building_department",
    permitPhone: "(850) 981-7075",
    permitEmail: "building@santarosa.fl.gov",
    description: "Santa Rosa County Building Department serves the western Panhandle with military and coastal development permits.",
  },
  {
    id: "sarasota",
    name: "Sarasota County",
    slug: "sarasota",
    websiteUrl: "https://www.scgov.net/government/building-and-development-services",
    permitPhone: "(941) 861-5000",
    permitEmail: "building@scgov.net",
    description: "Sarasota County Building and Development Services manages permits for the cultural coast with high-end development requirements.",
  },
  {
    id: "seminole",
    name: "Seminole County",
    slug: "seminole",
    websiteUrl: "https://www.seminolecountyfl.gov/departments-services/development-services/building-department/",
    permitPhone: "(407) 665-2400",
    permitEmail: "building@seminolecountyfl.gov",
    description: "Seminole County Building Department serves the northern Orlando metropolitan area with suburban development permits.",
  },
  {
    id: "sumter",
    name: "Sumter County",
    slug: "sumter",
    websiteUrl: "https://www.sumtercountyfl.gov/departments/building_department",
    permitPhone: "(352) 569-6040",
    permitEmail: "building@sumtercountyfl.gov",
    description: "Sumter County Building Department serves The Villages region with age-restricted community development permits.",
  },
  {
    id: "suwannee",
    name: "Suwannee County",
    slug: "suwannee",
    websiteUrl: "https://www.suwanneecounty.org/departments/building_department",
    permitPhone: "(386) 362-3964",
    permitEmail: "building@suwanneecounty.org",
    description: "Suwannee County Building Department serves the Suwannee River region with rural and agricultural permits.",
  },
  {
    id: "taylor",
    name: "Taylor County",
    slug: "taylor",
    websiteUrl: "https://www.taylorcountygov.com/building-department",
    permitPhone: "(850) 838-3506",
    permitEmail: "building@taylorcountygov.com",
    description: "Taylor County Building Department serves the Big Bend region with coastal and forestry development permits.",
  },
  {
    id: "union",
    name: "Union County",
    slug: "union",
    websiteUrl: "https://www.unioncountyfl.gov/building-department",
    permitPhone: "(386) 496-2621",
    permitEmail: "building@unioncountyfl.gov",
    description: "Union County Building Department serves the rural North Central Florida region with agricultural permits.",
  },
  {
    id: "volusia",
    name: "Volusia County",
    slug: "volusia",
    websiteUrl: "https://www.volusia.org/services/community-services/building-permits-inspections/",
    permitPhone: "(386) 736-5959",
    permitEmail: "building@volusia.org",
    description: "Volusia County Building Permits and Inspections serves the Daytona Beach area with motorsports and coastal development permits.",
  },
  {
    id: "wakulla",
    name: "Wakulla County",
    slug: "wakulla",
    websiteUrl: "https://www.mywakulla.com/departments/building_department",
    permitPhone: "(850) 926-0500",
    permitEmail: "building@mywakulla.com",
    description: "Wakulla County Building Department serves the Big Bend region with coastal and environmental permits.",
  },
  {
    id: "walton",
    name: "Walton County",
    slug: "walton",
    websiteUrl: "https://www.co.walton.fl.us/departments/building_department",
    permitPhone: "(850) 892-8115",
    permitEmail: "building@co.walton.fl.us",
    description: "Walton County Building Department serves the Emerald Coast with luxury coastal development permits.",
  },
  {
    id: "washington",
    name: "Washington County",
    slug: "washington",
    websiteUrl: "https://www.washingtonfl.com/departments/building_department",
    permitPhone: "(850) 638-6285",
    permitEmail: "building@washingtonfl.com",
    description: "Washington County Building Department serves the rural Panhandle region with agricultural and forestry permits.",
  }
];

async function populateCounties() {
  try {
    console.log("Populating Florida counties...");
    
    for (const county of floridaCounties) {
      await db.insert(counties).values(county).onConflictDoNothing();
      console.log(`Added ${county.name}`);
    }
    
    console.log("Successfully populated all 67 Florida counties!");
  } catch (error) {
    console.error("Error populating counties:", error);
  }
}

populateCounties();